homeassistant:
  name: Berlin
  latitude: 52.52
  longitude: 13.40
  elevation: 34
  unit_system: metric
  time_zone: Europe/Berlin

default_config:

python_script:

automation:
  - alias: 'Mock DWD State on Startup'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: python_script.mock_dwd

  - alias: 'Mock DWD State Periodically'
    trigger:
      - platform: time_pattern
        seconds: '/10'
    action:
      - service: python_script.mock_dwd

lovelace:
  resource_mode: yaml
  resources:
    - url: /local/dist/nina-dwd-card.js
      type: module
  dashboards:
    lovelace:
      mode: yaml
      filename: ui-lovelace.yaml
      title: Overview
      icon: mdi:view-dashboard
      show_in_sidebar: true

template:
  - sensor:
      - name: dwd_mock_current_warning_level
        unique_id: dwd_mock_current_warning_level_unique
        state: '4'
        attributes:
          warning_1_headline: 'Amtliche WARNUNG vor extremer HITZE'
          warning_1_description: 'Am Sonntag wird eine extreme Wärmebelastung bis zu einer Höhe von 400m erwartet. Am Montag wird eine extreme Wärmebelastung bis zu einer Höhe von 400m erwartet. Heute ist der 4. Tag der Warnsituation in Folge.'
          warning_1_level: 4
          warning_1_start: '{{ (now() - timedelta(hours=5.5)).isoformat() }}'
          warning_1_end: '{{ (now() + timedelta(hours=26)).isoformat() }}'
          warning_1_instruction: 'Gefahr durch: mögliche erhebliche Frostschäden; Unterkühlung bei längerem Aufenthalt im Freien; einfrierende Wasserleitungen. Handlungsempfehlungen: Frostschutzmaßnahmen ergreifen, z.B. Pflanzen abdecken oder Wasser aus Außenleitungen ablassen; längere Aufenthalte im Freien vermeiden'
          warning_1_type: 1
      - name: dwd_mock_advance_warning_level
        unique_id: dwd_mock_advance_warning_level_unique
        state: '0'
  - binary_sensor:
      - name: warning_berlin_1
        state: 'on'
        attributes:
          headline: 'Amtliche WARNUNG vor extremer HITZE'
          description: 'Am Sonntag wird eine extreme Wärmebelastung bis zu einer Höhe von 400m erwartet.<br/><br/>Am Montag wird eine extreme Wärmebelastung bis zu einer Höhe von 400m erwartet.<br/><br/>Heute ist der 4. Tag der Warnsituation in Folge.'
          sender: 'Zentrum für Medizin-Meteorologische Forschung'
          severity: 'Extreme'
          start: '{{ (now() - timedelta(hours=7)).isoformat() }}'
          expires: '{{ (now() + timedelta(hours=26)).isoformat() }}'
          instruction: 'Gefahr durch: <br/> · mögliche erhebliche Frostschäden<br/> · Unterkühlung bei längerem Aufenthalt im Freien<br/> · einfrierende Wasserleitungen<br/><br/>Handlungsempfehlungen: <br/> · Frostschutzmaßnahmen ergreifen, z.B. Pflanzen abdecken oder Wasser aus Außenleitungen ablassen<br/> · längere Aufenthalte im Freien vermeiden'
          id: 'mow.de.ber.12345'
          sent: '{{ (now() - timedelta(hours=7)).isoformat() }}'
